/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [{type: 'autogenerated', dirName: 'INSTALL'}],
  app: [{type: 'autogenerated', dirName: 'INSTALL/apprecommend'}],
  lpath: [{type: 'autogenerated', dirName: 'lpath'}],
  desktop: [{type: 'autogenerated', dirName: 'desktop'}],
  //studySidebar: [{type: 'autogenerated', dirName: 'study'}],
  // But you can create a sidebar manually
  
/* docs: [
    {
      type: 'category',
      label: '安装指南',
      items: ['archinstall/config', 'archinstall/index'],
    },
    
  ],*/
};

module.exports = sidebars;
